### ISSUE TITLE
关于图片加载问题的缓存问题

### ISSUE THREAD

**Issue by HackerYunen** [Troy-Yang/hexo-lazyload-image#10]
随机事件，有时已经明明访问了图片，也取到了图片内容，但却不进入img.onload函数，替换url。
百度了一下，好像是由于缓存的问题，导致图片的懒加载没有进入onload函数。
我的临时解决方法：删掉simple-lazyload.js里的img.onload = function(){} 前置条件

**Comment by Troy-Yang** [comment]
请问你说的前置条件是哪个呢？能否看下你调查的缓存问题链接？

**Comment by HackerYunen** [comment]
抱歉，刚刚测试发现是与我自己添加的另一个js文件 (与图片标签有关) 有未知冲突所导致，代码本身无问题，此issue关闭。
