### ISSUE TITLE
Valine 评论系统里的表情图片没有懒加载

### ISSUE THREAD

**Issue by LiYanan2004** [Troy-Yang/hexo-lazyload-image#11]

**Comment by Troy-Yang** [comment]
表情图片是不能的，因为他不是使用img标签，大部分都是使用的font icon，所以这种是不支持的，也没办法

**Comment by LiYanan2004** [comment]
![image](https://user-images.githubusercontent.com/37542129/60641902-6d575600-9e60-11e9-9bf8-fcc5349ba699.png)
确实使用了img标签
