### ISSUE TITLE
一些优化改进建议

### ISSUE THREAD

**Issue by hvnobug** [Troy-Yang/hexo-lazyload-image#14]
> 作者的插件确实很好用
> 使用起来也很方便
> 经过这段时间的使用,发现有一些可以优化的地方

1. `const imgRegExp = /<img(\s*?)src="(.*?)"(.*?)>/gi;` 正则表达式只能匹配 第一个属性是 src 的 img 标签,对于像 &lt;img class="logo" src="/images/logo.png"/&gt; 无法匹配到。(建议改为`const imgRegExp = /<img(.*?)src="(.*?)"(.*?)>/gi;`)
2. 可以提供基于 class 或 属性 的 skip 策略,跳过一些小图片
3. 可以跳过对 base64 图片的懒加载

**Comment by Troy-Yang** [comment]
建议非常棒，三点都已经改过了。针对1 额外加了UT，  2 加了no-lazy:)
