### ISSUE TITLE
一个小小的建议

### ISSUE THREAD

**Issue by iChrAlpha** [Troy-Yang/hexo-lazyload-image#15]
作者好，实话说，这是我用过最棒的图片 lazyload 插件。但是在使用的过程中出现了一点点问题。

如果我以过快的速度划过页面，导致图片还没加载出来就过去了。由于懒加载仅仅加载正在屏幕中的图片，所以那张图片不会被加载出来。

所以，我认为，可以将机制设为如果过了那个位置，就加载那张图片，不论是否在页面内，不然有些稍微大一点的图片，别人一下过去就没有机会看到了。

仅仅个人见解，如果有更好的解决方案还请指教。

**Comment by Troy-Yang** [comment]
首先谢谢你的肯定。

对于你的建议，我认为只有当出现在视图内才能去请求图片这种做法是图片懒加载的普遍行为。而你说的“大一点的图片，如果一下过去就没机会看到了”这点我不是很明白，这个情况应该不会发生的，如果滑动太快，然后再回去到图片视图里是可以让图片加载的，至于能不能加载出图片就得看情况了，也许网络差或者图片地址出问题都可能导致。不知道有没有可能哈，滚动条滑动时，我设置的图片加载间隔是500毫秒。

有一点是，从loading图片到请求真实图片，只会有一次请求，并且不可逆，能请求成功就成功，不成功就不会再次尝试。

**Comment by Troy-Yang** [comment]
@ChrAlpha 似乎了解了你的问题，“大一点的图片，如果一下过去就没机会看到了”，快速滚动，然后往上滑动，之前是在这种情况下，只有当图片完全在视图内才会加载图片，现在已经修复了，只要有部分图片在视图内也会加载

谢谢你的问题，非常好，没想到小小的视图内的判定还会有这么多讲究。。。

**Comment by iChrAlpha** [comment]
> @ChrAlpha 似乎了解了你的问题，“大一点的图片，如果一下过去就没机会看到了”，快速滚动，然后往上滑动，之前是在这种情况下，只有当图片完全在视图内才会加载图片，现在已经修复了，只要有部分图片在视图内也会加载
> 
> 谢谢你的问题，非常好，没想到小小的视图内的判定还会有这么多讲究。。。

正是！这几天处理别的去了，没有注意这边，抱歉上次的描述不清晰～
