### ISSUE TITLE
与Fancybox同时启用时产生冲突

### ISSUE THREAD

**Issue by UPWNothing** [Troy-Yang/hexo-lazyload-image#17]
在Hexo中同时启用该插件与Fancybox时，图片点开后Fancybox展示的图片为站位图片。

Fancybox 在页面加载时就会给页面中所有的图片套一层a标签，a标签的href就是图片的src，也就是站位图片。

不知道这个问题是否有办法解决。

同时也借此感谢作者分享这个很棒的插件，除去上述问题外，非常好用。: )

**Comment by Troy-Yang** [comment]
谢谢，

鉴于很多人都遇到这个兼容性问题，我已经在最新的版本里专门修复了这个问题，请尝试。
