### ISSUE TITLE
安装插件后主页出现文字无法显示，只有博客框架和背景图片，请问怎么解决或者卸载

### ISSUE THREAD

**Issue by sfershmiss11** [Troy-Yang/hexo-lazyload-image#20]

**Comment by Troy-Yang** [comment]
主题用的啥？有在线连接最好，卸载直接把相应插件配置删除就可以了

**Comment by sfershmiss11** [comment]
用的next，仓库是github
sfershmiss11.github.io



在 2020-02-27 16:10:46，"杨舟" <notifications@github.com> 写道：

主题用的啥？有在线连接最好，卸载直接把相应插件配置删除就可以了

**Comment by sfershmiss11** [comment]
但是我用了Cloudflare解析







在 2020-02-27 16:10:46，"杨舟" <notifications@github.com> 写道：

主题用的啥？有在线连接最好，卸载直接把相应插件配置删除就可以了

**Comment by Troy-Yang** [comment]
试了hexo-theme-next landscape 几个主题，都没重现
