### ISSUE TITLE
关于与 Pjax 的兼容问题

### ISSUE THREAD

**Issue by inkss** [Troy-Yang/hexo-lazyload-image#21]
我在代码里看到有关以下内容：

https://github.com/Troy-Yang/hexo-lazyload-image/blob/a0f18cb4e4621477376867558bcd6a25a76951bb/lib/simple-lazyload.js#L47

Pjax 跳转页面后，相关的事件监听便都停止了，可以抛给外界一个可供重新调用的接口吗？

**Comment by inkss** [comment]
我觉得还是你这边抛出来个接口好，我这边为了兼容，几乎重新写了一遍 `simple-lazyload.js` 这个文件，去重复调用它。

**Comment by Troy-Yang** [comment]
我想问下pjax会把window上的事件清空？

你是期望我暴露一个processImage或者throttle给外部？

**Comment by inkss** [comment]
嗯，跳转页面后一些监听没了，暴漏一个可以起到重新监听的方法就行，因为我现在就相当于把 simple-lazyload.js 里整个内容当作一个函数，在加载完成后重新调用了一遍。

**Comment by Troy-Yang** [comment]
已经加了相应的API，需要额外指定配置 **exportAPI** 为true， 然后就可以从widow上获取
`
window.imageLazyLoadSetting = {
  processImages, // core method to process lazyload image
  processImagesThrottle, // throttle to process image with per 500 millisecond
};
`

**Comment by inkss** [comment]
我好像发现了一个比较尴尬的点，因为一直不太知道这边的加载时机，再加上在切换页面时执行了`$(document, window).unbind('scroll');`，就下意识认为图片加载不出来是因为事件丢了的缘故。

刚刚我又试了下，似乎好像只要把：

```js
var images = Array.prototype.slice.call(document.querySelectorAll('img[data-original]'));
```
扔到 processImages() 函数里就可以，lazyload 是在什么时候被初始化调用的啊？ @Troy-Yang

**Comment by Troy-Yang** [comment]
我花了些时间去看你们的 volantis 3.0 PJAX版本，根本的原因是因为你们的PJAX  版本是一个SPA 页面版本，导致整个过程页面只会加载一次，而lazyload 找寻当前页面所有images也只会找一次，当页面跳转的时候，存储的images还是上一个页面的，所以页面跳转后就不工作了。

解决方案我已经改了一版了，加了一个配置 **isSPA**，设置为true就好了， 改动也和你说的差不多，如果是spa页面，则把找寻image 过程放processimages里

试试v1.0.9 @inkss

**Comment by inkss** [comment]
好使了，非常完美 √
