### ISSUE TITLE
页面第一加载之后再刷新图片就不再加载了

### ISSUE THREAD

**Issue by avdance** [Troy-Yang/hexo-lazyload-image#24]
页面第一加载之后再刷新图片就不再加载了，这是一个重严重的BUG，有什么好的办法解决吗？

**Comment by Troy-Yang** [comment]
可以描述多一点吗？主题是用的什么呢？是否单页面？测试了下最新的版本，没发现问题，按理刷新页面从技术上看不应该会有这种问题的

**Comment by meethigher** [comment]
> 页面第一加载之后再刷新图片就不再加载了，这是一个重严重的BUG，有什么好的办法解决吗？

不知道你说的加载，是指在页面显示出来，还是在浏览器访问时重新载入图片。如果是第一种，有可能是你主题的问题；如果是第二种的话，你需要在调试时清除缓存，或者禁用浏览器缓存。
