### ISSUE TITLE
onlypost is not work

### ISSUE THREAD

**Issue by shenqiuhui** [Troy-Yang/hexo-lazyload-image#26]

**Comment by Troy-Yang** [comment]
I tried the setting below with latest version, but didn't find the issue:
`
  enable: true
  onlypost: true # optional
  loadingImg: # optional eg ./images/loading.gif
  isSPA: false
`
You can try to inspect any image element to check it support the lazy or not. If it has **data-original**, then the image will be lazied.
`
<img src="/images/avatar.png" data-original="/images/avatar.png">
`

let me know more detail like which theme you are using if you want me to dig into.

**Comment by Troy-Yang** [comment]
recreated under icarus theme. https://github.com/Troy-Yang/hexo-lazyload-image/issues/47
