### ISSUE TITLE
[FR] Load before it comes into the browser viewport

### ISSUE THREAD

**Issue by benwinding** [Troy-Yang/hexo-lazyload-image#29]
Great plugin, and there's no problem with it.

Maybe this code here :arrow_down:  could be updated to begin loading before it's visible in the viewport. I think this would improve the experience greatly.

https://github.com/Troy-Yang/hexo-lazyload-image/blob/85769aeb20687e4cbb60245c72075495399080ae/lib/simple-lazyload.js#L6-L13

Cheers,
Ben

**Comment by Troy-Yang** [comment]
Hey Ben,

Perhaps I didn't get what's your point, I think lazy loading means to load the current screen images only, do you mean to pre-load partial(not all) images where is not in current viewport?

I think it's maybe a good idea to preload the images with 2x or 3x screen size by providing a new option like **preloadRatio**.

What's your point?

**Comment by benwinding** [comment]
Hi @Troy-Yang,

Thanks for the response! 

> I think lazy loading means to load the current screen images only

Well, lazy-loading means to simply load content when _necessary_, it doesn't have to be only when it becomes visible on the screen. If you load images just before the user scrolls to them, it would still be considered lazy-loading.

> I think it's maybe a good idea to preload the images with 2x or 3x screen size by providing a new option like preloadRatio.

That's a great idea :+1:, and would make it an even better plugin!! Would that be hard to implement?

Cheers,
Ben

**Comment by Troy-Yang** [comment]
Hey @benwinding 

Yes, I agreed with lazy-load images means to load them when **necessary**. Just like this link mentioned: https://css-tricks.com/the-complete-guide-to-lazy-loading-images/#chapter-2-why-lazy-load-at-all

> Would that be hard to implement?

Not at all. This idea inspired by map engine, they often load more tiles than current size. checkout this MR https://github.com/Troy-Yang/hexo-lazyload-image/pull/30 

I will merge it after some tests.

Thanks for your heads up anyway! Have a nice Friday!

**Comment by benwinding** [comment]
Thanks @Troy-Yang! 
Looks like a very simple update, well done :+1:
