### ISSUE TITLE
Not working properly on firefox

### ISSUE THREAD

**Issue by sira313** [Troy-Yang/hexo-lazyload-image#4]
I've tried to change `loadingImg: /img/loading.gif`with my own logo with 450x450px. The issue start when i open some post, then back to home again just like this video.
https://streamable.com/3zj7r
I've tried to run on localhost but there's no error log.
Now, i change the `loadingImg` back to default.
I use [Hexo-theme-magnetic](https://github.com/klugjo/hexo-theme-magnetic)

**Comment by Troy-Yang** [comment]
Could you try loadingImg: ./img/loading.gif ? Let me know if it persists.

**Comment by sira313** [comment]
> Could you try loadingImg: ./img/loading.gif ? Let me know if it persists.

wow, it's work. thank you

**Comment by Troy-Yang** [comment]
Nope. I should thank you as It proved I need to update the documentation now.
