### ISSUE TITLE
回调函数

### ISSUE THREAD

**Issue by jack-thegeek** [Troy-Yang/hexo-lazyload-image#43]
hello 作者大大，请问能添加个回调函数吗，我遇到了与[这篇文章](https://www.paincker.com/masonry-lazyload-waterfall/)类似的问题，就是瀑布流计算的时候用的loading.gif的大小，img的src被替换后没办法触发重新计算。另外我用的是 [macy.js](https://github.com/bigbite/macy.js) 这个插件，感谢！

**Comment by Troy-Yang** [comment]
嗯，这个可以有，新增了个API `onImageLoaded`, 试试呢，但是不确定如果每张图片加载后都触发macy的重新计算，不确定是否会有性能问题 
`
window.imageLazyLoadSetting.onImageLoaded = (img) => console.log(img.src)
`

**Comment by Troy-Yang** [comment]
嗯，这个可以有，新增了个API `onImageLoaded`, 试试呢，但是不确定如果每张图片加载后都触发macy的重新计算，不确定是否会有性能问题 
`
window.imageLazyLoadSetting.onImageLoaded = (img) => console.log(img.src)
`
