### ISSUE TITLE
script.js文件中修改了97后前四张图还是loading占位

### ISSUE THREAD

**Issue by xcxhy** [Troy-Yang/hexo-lazyload-image#44]
我根据你的说的修改了script.js文件中的97行后，每篇博客的前四张图片点开还是loading占位图，但是剩下的图片正常，有什么解决方法吗？

我测试了一下，是由于isSPA设置为true的时候，preloadRatio默认为1时，由于我第一张图就在正面就不会懒加载，这时就会导致fancybox点不了该图片。

目前解决了，把暴露在首页的图片设置nolazy才可以解决，有别的解决方法吗

**Comment by Troy-Yang** [comment]
可以给个你用的主题或者在线blog 吗？不是很确定问题原因，只能猜测可能是 third-party-fix.js 这个文件执行顺序的问题

**Comment by xcxhy** [comment]
我是使用的就是Next的主题。我昨天发现图片设置nolazy后，就会在首页预览全文的时候滑动情况下不加载nolazy图片

**Comment by Troy-Yang** [comment]
抱歉才回复，一直没重现问题， 请问这个问题在Next 下现在还有吗？如果还有，其实现在不需要手动修改scripts.js 文件，你可以删除试试看。

最近发现，如果图片地址不对导致加载失败，也会导致一直处于loading 图片状态。
