### ISSUE TITLE
如何取消某页面懒加载

### ISSUE THREAD

**Issue by ljnMeow** [Troy-Yang/hexo-lazyload-image#49]
请教下如何取消某个页面的图片懒加载

**Comment by Benn314** [comment]
请教下如何取消某个页面的图片懒加载，是否可以通过front-matter进行设置？

**Comment by Troy-Yang** [comment]
嗯，最近抽空加上了，可在post 的front-matter 添加属性关闭：
```
lazyimage: no
```

**Comment by Benn314** [comment]
Ben已收到您的邮件，我会尽快处理，谢谢，祝您生活愉快
