### ISSUE TITLE
next开启懒加载后报错

### ISSUE THREAD

**Issue by GeekBookx** [Troy-Yang/hexo-lazyload-image#50]
hexo版本 6.3.0
next 6.0
git version 2.38.1.windows.1
当开启懒加载后hexo g出现以下信息，是怎么回事呢？
我的图片全部放在腾讯云的对象储存里。
![problem](https://alpha-1253902598.cos.ap-guangzhou.myqcloud.com/1222.jpg)

**Comment by Yancey597** [comment]
哥，我也是这样，现在好了吗

**Comment by GeekBookx** [comment]
> 哥，我也是这样，现在好了吗
虽然报错但是可以正常用的我就没管了
后来升级主题next到最新版本7还是8来着就用next自带的懒加载，把这个插件卸了。

**Comment by Yancey597** [comment]
> > 哥，我也是这样，现在好了吗
> > 虽然报错但是可以正常用的我就没管了
> > 后来升级主题next到最新版本7还是8来着就用next自带的懒加载，把这个插件卸了。

好的谢谢

**Comment by Troy-Yang** [comment]
是的，next现在自带lazyload，但看起来是全页面替换，并没提供此插件的其他功能

**Comment by Troy-Yang** [comment]
> hexo版本 6.3.0 next 6.0 git version 2.38.1.windows.1 当开启懒加载后hexo g出现以下信息，是怎么回事呢？ 我的图片全部放在腾讯云的对象储存里。 ![problem](https://camo.githubusercontent.com/d4f519104bc314d433024fa2eba85ecd65bf040fe1c523341f5037fc21e3eabb/68747470733a2f2f616c7068612d313235333930323539382e636f732e61702d6775616e677a686f752e6d7971636c6f75642e636f6d2f313232322e6a7067)

从截图来看，看不出什么线索，只看到一个 hexo-blog-encrypt  可能因素。另外你是hexo generate 的时候将图片上传至云服务，然后得到图片domain 地址的吗？

**Comment by GeekBookx** [comment]
> > hexo版本 6.3.0 next 6.0 git version 2.38.1.windows.1 当开启懒加载后hexo g出现以下信息，是怎么回事呢？ 我的图片全部放在腾讯云的对象储存里。 ![problem](https://camo.githubusercontent.com/d4f519104bc314d433024fa2eba85ecd65bf040fe1c523341f5037fc21e3eabb/68747470733a2f2f616c7068612d313235333930323539382e636f732e61702d6775616e677a686f752e6d7971636c6f75642e636f6d2f313232322e6a7067)
> 
> 从截图来看，看不出什么线索，只看到一个 hexo-blog-encrypt 可能因素。另外你是hexo generate 的时候将图片上传至云服务，然后得到图片domain 地址的吗？

我是把图片上传到云，md文件里面插入图片时，使用网络地址。
那可能是hexo-blog-encrypt插件的问题，不过我也已经很久不用这个插件了，自从更新next之后。

**Comment by Troy-Yang** [comment]
如果 hexo-blog-encrypt 问题，可参考 https://github.com/Troy-Yang/hexo-lazyload-image/issues/54
