### ISSUE TITLE
与 fancybox 的兼容问题

### ISSUE THREAD

**Issue by GZ-Metal-Cell** [Troy-Yang/hexo-lazyload-image#53]
这个插件还是将真实数据存在 data-original 中，这会与 fancybox 冲突，根据 https://github.com/fancyapps/fancybox/issues/1430 里所说，应该设为 data-src，如何做到这点？

**Comment by GZ-Metal-Cell** [comment]
或者说，如何自定义 data-original 为其他属性？

**Comment by Troy-Yang** [comment]
现在还有兼容性问题吗？ 按说这个已经修复过兼容性问题了 https://github.com/Troy-Yang/hexo-lazyload-image/issues/17

**Comment by GZ-Metal-Cell** [comment]
懂了，要将创建 fancybox 时 <a> 的 href 和 data-thumb 设为 data-original 才可以生效...
