### ISSUE TITLE
使用这个插件后，无法放大原图了，放大后全是loading.gif

### ISSUE THREAD

**Issue by wyx1818** [Troy-Yang/hexo-lazyload-image#7]
![image](https://user-images.githubusercontent.com/31715036/55610429-79763d80-57b5-11e9-820f-4cf436bfcf59.png)
详见zuiyu1818.cn，文章内所有图片点放大全都变成loading了...

**Comment by Troy-Yang** [comment]
参见
https://github.com/Troy-Yang/hexo-lazyload-image/issues/1

**Comment by wyx1818** [comment]
已解决，谢谢

**Comment by wyx1818** [comment]
> 参见
> #1

已经参考解决，谢谢
