### ISSUE TITLE
对于fancybox，我按照 #1 的方式修改了，发现无效

### ISSUE THREAD

**Issue by wyx1818** [Troy-Yang/hexo-lazyload-image#8]
![image](https://user-images.githubusercontent.com/31715036/55615212-649fa700-57c1-11e9-9704-ee7f865b460e.png)
我将第九行改成了

![image](https://user-images.githubusercontent.com/31715036/55615149-4043ca80-57c1-11e9-93c9-c4f2aed861aa.png)

发现还是无效

**Comment by wyx1818** [comment]
https://b.zuiyu1818.cn

**Comment by Troy-Yang** [comment]
试试这个：
<script>
    $(document).find('img[data-original]').each(function(){
        $(this).parent().attr("href", $(this).attr("data-original"));
    });
</script>

**Comment by wyx1818** [comment]
> 试试这个：
> 
> <script> $(document).find('img[data-original]').each(function(){ $(this).parent().attr("href", $(this).attr("data-original")); }); </script>

成功啦，麻烦您啦

**Comment by Troy-Yang** [comment]
已经在最新的1.0.6版本里修复了这个问题，再也不用大家手动去改啦
