### ISSUE TITLE
区域前预加载

### ISSUE THREAD

**Issue by Lruihao** [Troy-Yang/hexo-lazyload-image#9]
请详见<https://lruihao.cn/docs/>
![QQ截图20190520173906.png](https://i.loli.net/2019/05/20/5ce275c56c3da22907.png)

**Comment by Lruihao** [comment]
其中有一张图片可以加载出来(它是放在文章的图片文件夹内)，其他无法加载的图片全是放在`/dos/images/`文件里的。有时间的话麻烦看看😃谢谢！

**Comment by Troy-Yang** [comment]
贴出你的配置，和图片目录结构，我看其中一张生成图片地址为 https://lruihao.cn/docs/dos/images/cpu2.png， 请查看目录是否正确

**Comment by Lruihao** [comment]
> 贴出你的配置，和图片目录结构，我看其中一张生成图片地址为 [https://lruihao.cn/docs/dos/images/cpu2.png，](https://lruihao.cn/docs/dos/images/cpu2.png%EF%BC%8C) 请查看目录是否正确

尴尬！打扰了！我自己的问题。还有一个就是请问这个懒加载可不可以设置在可视区域前一点点加载，比如说可视区前50px就开始加载。感觉进入可视区后再加载有一点点慢。

**Comment by Troy-Yang** [comment]
load 慢的问题可能需要看看是不是你的图片托管地址加载有点慢，一般lazyload不会做这些配置。你的建议不错，不过不确定其他人有没有类似需要，我可以暂时列为enhancement
